### ISSUE TITLE
feature request: method to reset spectrum on device

### ISSUE THREAD

**Issue by GuenterQuast** [cdump/radiacode#12]
I am considering the RadiaCode 102 device as a replacement for older hardware in a physics lab course. 
Low-level actions for students, control of data acquisition rely on your python-interface (thank you very much
for providing this").   
I could not figure out how it is possible to reset spectrum (and dose) in the device - this is possible using the
Android or windows apps.  Is this also possible using the python library ? 
If so, please tell me, if not , it would be nice to  implement this feature in a coming release.

**Comment by cdump** [comment]
Added in v0.2.1 - [2 new functions](https://github.com/cdump/radiacode/commit/cac4209431e23f4a7e61ba831188c927101b4b6d#diff-8432e46afca3af1ff9194c636d8c2359c1067eef0a13e9749fcd88f533441c95R143), please check.

p.s. how are you getting dose? It's in [RareDate](https://github.com/cdump/radiacode/blob/master/radiacode/types.py#L37), this messages are really rare and I can't find a way to request it "right now".
