### ISSUE TITLE
radiacode-examples/show-spectrum.py PyYAML dependency and documentation.

### ISSUE THREAD

**Issue by mkgin** [cdump/radiacode#21]
I started playing with radiacode-examples in a clean python virtual environment today

After installing, it works ok for me via USB (linux),  Radiacode FW 4.7. 

This demo looks nice but it depends on PyYAML.  (I needed to install it manually)

Also, the "--noreset" option could be mentioned in the documentation. Just in case someone had been interested in spectrum data collected over the last few hours :smile:   ... Maybe "--noreset" could be default behavior and a option to "--reset"

**Comment by cdump** [comment]
I've fixed missing deps in v0.3.0
Let's discuss --noreset defaults with author of this script @GuenterQuast

**Comment by ckuethe** [comment]
I'm of the mind that a tool called "show" should not do any kind of "change", "update", "modify", "clear", "reset" ... operation without explicit intent.

In [radiacode_poll.py](https://github.com/ckuethe/radiacode-tools/blob/main/src/radiacode_poll.py), I grab the current spectrum when the program starts and use that at the baseline for subsequent accumulation. That's sufficient to allow me to show  the accumulation during the sampling interval without changing the state in memory.

**Comment by mkgin** [comment]
> I'm of the mind that a tool called "show" should not do any kind of "change", "update", "modify", "clear", "reset" ... operation without explicit intent.
> 
> In [radiacode_poll.py](https://github.com/ckuethe/radiacode-tools/blob/main/src/radiacode_poll.py), I grab the current spectrum when the program starts and use that at the baseline for subsequent accumulation. That's sufficient to allow me to show the accumulation during the sampling interval without changing the state in memory.

I've seen radiacode-tools. The Sandia labs SW looks interesting,  I'm using Linux_ and iOS daily... windows only when absolutely necessary... so some way to use that is interesting. Being able to use this library to export enough xml

Radiacode 102 arrived yesterday :-) so far I have been using the webserver example to download a CSV and then display with gnuplot. (Linux and iOS daily... windows only when absolutely necessary... )

**Comment by ckuethe** [comment]
Gettin' a little off topic now, but today's project is to make something that renders spectrograms using matplotlib and all the pretty palettes it supports.

Anyhoo, cdump's radiacode library is amazeballs.

**Comment by GuenterQuast** [comment]
Thanks for taking care of the firmware adjustments !

Concerning the defaults in show_spectrum.py: 
  I agree that as part of this repository, resetting the device by default is confusing. (I developed the script for data acquisition in physics lab courses, where starting under "clean" conditions is appropriate).  I'll provide a version with
more reasonable defaults soon.

**Comment by mkgin** [comment]
Thanks!
