### ISSUE TITLE
Contents of the byte array requests

### ISSUE THREAD

**Issue by davidcarlsonSEE** [cdump/radiacode#25]
Hi,

Three questions

Question 1.  I'm confused, why do some of the requests have an & character? 
full_request=[b'\x08\x00\x00\x00&\x08\x00\x97\x00\x01\x00\x00']  //this while looping for readings

Question 2. Or % and \n characters for that matter?
Init
full_request[b'\x08\x00\x00\x00\x07\x00\x00\x80\x01\xff\x12\xff'] //straight byte array 

localtime
full_request[b'\x0c\x00\x00\x00\x04\n\x00\x81\x17\x01\x18\x00\x1d$\x0b\x00'] //this has a \n

devicetime
full_request[b'\x0c\x00\x00\x00%\x08\x00\x82\x04\x05\x00\x00\x00\x00\x00\x00'] \\this has a %

version
full_request[b'\x04\x00\x00\x00\n\x00\x00\x83']   //This one has a \n 

Question 3. Are the write request byte arrays the same for the BLE characteristics?

Thanks.

**Comment by cdump** [comment]
Hi
When you `print(byte_var)` in python it prints ASCII characters as-is:
```python
In [1]: b'\x41\x30\x31\x00\x01'
Out[1]: b'A01\x00\x01'
```

You can use `.hex()` to output every char as hex:
```python
In [2]: b'\x41\x30\x31\x00\x01'.hex()
Out[2]: '4130310001'
```

I don't understand question 3, can you describe it in more detail?

**Comment by davidcarlsonSEE** [comment]
Thanks for the .hex() hint!  I'm a c++, c#, java so I'm translating python.

Now my debug looks much better.
full_request=[080000002608009300010000]   which returns:
2024-01-23T14:35:30.246307 RealTimeData(dt=datetime.datetime(2024, 1, 23, 14, 35, 30, 246307), count_rate=4.8125, count_rate_err=5.6, dose_rate=6.796455181756755e-06, dose_rate_err=20.3, flags=8256, real_time_flags=0)

So Question 3.
I'm tasked to code an Android java Bluetooth app to request the spectra, readings, n42, any data I can get.
Question 3 is asking do I writeCharacteristic  with the same byte array on Bluetooth like USB? 

For instance, in bluetooth.py function execute the line `self.p.writeCharacteristic(self.write_fd, rp)` will rp be the same request bytes?  full_request=[080000002608009300010000].   (sequence number notwithstanding as it increments)

```
    def execute(self, req) -> BytesBuffer:
        for pos in range(0, len(req), 18):
            rp = req[pos : min(pos + 18, len(req))]
            self.p.writeCharacteristic(self.write_fd, rp)

        while self._response is None:
            self.p.waitForNotifications(2.0)

        br = BytesBuffer(self._response)
        self._response = None
        return br

```
Incidentally, is there a way to get the latest spectrum.XML file?  I'll have to periodically get that too.

**Comment by cdump** [comment]
> will rp be the same request bytes

yes, `def execute(self, req) -> BytesBuffer` is method of the interface and both [bluetooth.py](https://github.com/cdump/radiacode/blob/master/radiacode/transports/bluetooth.py#L42) and [usb.py](https://github.com/cdump/radiacode/blob/master/radiacode/transports/usb.py#L40) implement it

>  latest spectrum.XML

I don't know about spectrum.xml, looks like it's not part of the protocol, but something at a higher level

**Comment by davidcarlsonSEE** [comment]
In dozens of ble apps I've never seen notify_fd+1 `self.p.writeCharacteristic(notify_fd + 1, b'\x01\x00')`  
Why the +1?  

In c# you get the characteristic and call SetNotification(Characteristic, true);  

```
        service = self.p.getServiceByUUID('e63215e5-7003-49d8-96b0-b024798fb901')
        self.write_fd = service.getCharacteristics('e63215e6-7003-49d8-96b0-b024798fb901')[0].getHandle()
        notify_fd = service.getCharacteristics('e63215e7-7003-49d8-96b0-b024798fb901')[0].getHandle()
        self.p.writeCharacteristic(notify_fd + 1, b'\x01\x00')
```

**Comment by Am6er** [comment]
on C# i just call uuid without +1:

```C#
private const string RC_BLE_Notify = "e63215e7-7003-49d8-96b0-b024798fb901";
GattCharacteristicsResult charNotifyResult = await service.GetCharacteristicsForUuidAsync(Guid.Parse(RC_BLE_Notify));
```

**Comment by davidcarlsonSEE** [comment]
Thanks.  I just got it and made my first read from java.  The +1 must point to a descriptor of the characteristic.  

In my java code I setup for notifications like this:
```
boolean connectCharacteristics3(BluetoothGatt gatt)
        {
            BluetoothGattService gs            = gatt.getService(UUID_RadiaCodeCustomService);
            BluetoothGattCharacteristic gc     = gs.getCharacteristic(UUID_RadiaCodeCustomServiceCharacteristicdd1N);
            for (BluetoothGattDescriptor descriptor : gc.getDescriptors())
            {
                //descriptor.setValue( BluetoothGattDescriptor.ENABLE_INDICATION_VALUE);  //this way or
                descriptor.setValue(new byte[]{0x01, 0x00}); //this way
                gatt.writeDescriptor(descriptor);
                SystemClock.sleep(10);
            }
            gatt.setCharacteristicNotification   (gc,true);
            SystemClock.sleep(10);
            gatt.readCharacteristic(gc);

            onSerialConnect();
            connected = true;
            return true;
        }
```
And make the request like this: 
```
byte [] writeMe = hexStringToByteArray("080000002608008800010000");// a reading from the usb vsc test that worked
sc.setValue (writeMe);
boolean tf = gatt.writeCharacteristic(sc); //where sc=UUID.fromString("e63215e6-7003-49d8-96b0-b024798fb901");
```
Which triggers the onCharacteristicChanged (notify) function with the returned byte data.

Next I have to figure out and translate the python request commands I need to make, such as:
 `byte [] writeMe = hexStringToByteArray("080000002608008800010000");`   Which I believe is the request for current values.

Then port the decoders from python to java.  But I'm getting data so I'm ok.

**Comment by davidcarlsonSEE** [comment]
The Init request fr=[080000000700008001ff12ff] returns the following data:
init=[070000800501dada2020001001010000]
But I have not been able to find where this is decoded, there I don't see an entry in the VS enumeration.
Is this init returned data important enough to worry about? 
Does the init have to be called? 
What does the init request do?
