### ISSUE TITLE
Questions about how you created this

### ISSUE THREAD

**Issue by JoshuaKimsey** [cdump/radiacode#4]
Greetings! I just got my Radiacode-101 today and I absolutely love it. However, given I'm a Linux guy, I was curious to know how you went about reverse engineering this to work with the Radiacode? Do they have some open-source documentation somewhere describing how to access the data? Or did you just figure it out on your own?

I'm asking cause I'd love to make my own app for Linux to interact with the Radiacode. But I'd definitely like to know if there is a good way to go about accessing the data on it. Any help you can provide is great appreciated! :)

**Comment by cdump** [comment]
Hello!
I don't think publicly available protocol documentation exists.
I've [captured Bluetooth traffic](https://medium.com/propeller-health-tech-blog/bluetooth-le-packet-capture-on-android-a2109439b2a1) on my android phone while using official application and then "just read" it in Wireshark and tried to figure out what is what.
Decompilation official android app with [jadx](https://github.com/skylot/jadx) also helps me to understand some non-trivial moments.

**Comment by davidcarlsonSEE** [comment]
Hi.
Hmmmm my btsnooz_hci.log has an error:
wireshark the capture file appears to be damaged or corrupt bigger than maximum
I tried two different phones and two different android versions but I get the same thing?
Any suggestions while I google?
